### PR TITLE
Update to tomcat 9.0.31-1~deb10u4

### LINKED ISSUE #7: tomcat9_9.0.31-1~deb10u3_all.deb -- is gone from your FTP source.  deb10u4_all.deb exists.
conf/tomcat9_deb.src

SOURCE_URL=https://ftp.debian.org/debian/pool/main/t/tomcat9/tomcat9_9.0.31-1~deb10u3_all.deb

change to

SOURCE_URL=https://ftp.debian.org/debian/pool/main/t/tomcat9/tomcat9_9.0.31-1~deb10u4_all.deb

and update all instances of deb10u3 to deb10u4.

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem

Closes #7 

## Solution

- It is annoying that older builds are getting removed from source server, but whatever.
- Let's rename the downloaded archive to simplify the code.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
@Jules-Bertholet I think there is a slight issue with the backup and restore of the Tomcat9 service

> 6242 INFO [######++............] > Reinstalling dependencies...
6260 WARNING No files found for tomcat9.service.

**Comment by Jules-Bertholet** [comment]
Thanks for this!

**Comment by Jules-Bertholet** [comment]
@tituspijean There's no issue, other than the SystemD `--quiet` flag not working for some reason. The `no files found` is expected if you don't have Tomcat installed separately already.

**Pull request merged**
